project_id = "ecellnikwwjosdvlqsvu"

[functions.manage-restaurant-tables]
verify_jwt = false

[functions.restaurant-onboarding]
verify_jwt = false

[functions.reservation-email]
verify_jwt = false

[functions.reservation-reminder-cron]
verify_jwt = false
