// This file was originally auto-generated by Lovable.
// We keep the default exported `supabase` client, but also expose
// lightweight runtime configuration helpers so the preview can connect
// even when Vite env vars are not injected.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const FALLBACK_SUPABASE_URL = "https://ecellnikwwjosdvlqsvu.supabase.co";
// NOTE: This is the anon/publishable key. It is safe to ship to the browser.
const FALLBACK_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZWxsbmlrd3dqb3Nkdmxxc3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1OTE2NTEsImV4cCI6MjA4NDE2NzY1MX0.9wjdYceiVVUoxH0U6bz1hc5WTpOl0Sjjm0EiGwWZD2U";

const RUNTIME_CFG_KEY = "restaurant.supabase.runtime.v1";

export type RuntimeSupabaseConfig = {
  url?: string;
  anonKey?: string;
};

function normalizeUrl(url: string) {
  return url.trim().replace(/\/+$/, "");
}

export function getSupabaseConfig(): RuntimeSupabaseConfig & {
  source: "runtime" | "env" | "fallback";
} {
  // 1) Runtime override (stored in this browser)
  try {
    const raw = localStorage.getItem(RUNTIME_CFG_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as RuntimeSupabaseConfig;
      const url = parsed.url ? normalizeUrl(parsed.url) : undefined;
      const anonKey = parsed.anonKey?.trim() || undefined;
      if (url && anonKey) return { url, anonKey, source: "runtime" };
    }
  } catch {
    // ignore
  }

  // 2) Vite env (preferred when available)
  const envUrl = (import.meta as any).env?.VITE_SUPABASE_URL as string | undefined;
  const envAnon = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY as string | undefined;
  if (envUrl && envAnon) return { url: normalizeUrl(envUrl), anonKey: envAnon.trim(), source: "env" };

  // 3) Fallback hardcoded values (keeps demo working)
  return { url: FALLBACK_SUPABASE_URL, anonKey: FALLBACK_SUPABASE_ANON_KEY, source: "fallback" };
}

export function saveRuntimeSupabaseConfig(cfg: RuntimeSupabaseConfig) {
  const next: RuntimeSupabaseConfig = {
    url: cfg.url ? normalizeUrl(cfg.url) : "",
    anonKey: cfg.anonKey?.trim() ?? "",
  };
  localStorage.setItem(RUNTIME_CFG_KEY, JSON.stringify(next));
}

export function clearRuntimeSupabaseConfig() {
  localStorage.removeItem(RUNTIME_CFG_KEY);
}

export const supabaseConfigSource = getSupabaseConfig().source;
export const resolvedSupabaseUrl = getSupabaseConfig().url;
export const resolvedSupabaseAnonKey = getSupabaseConfig().anonKey;
export const isSupabaseConfigured = Boolean(resolvedSupabaseUrl && resolvedSupabaseAnonKey);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(resolvedSupabaseUrl!, resolvedSupabaseAnonKey!, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
