// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsiycjsumuiozlqhyofn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzaXljanN1bXVpb3pscWh5b2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NjAzNjcsImV4cCI6MjA5MjUzNjM2N30.fDqi7t_ag1iFwOLwmQk1Ns2Ma__hTPDCjwqDpy6bRFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});