// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecellnikwwjosdvlqsvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZWxsbmlrd3dqb3Nkdmxxc3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1OTE2NTEsImV4cCI6MjA4NDE2NzY1MX0.9wjdYceiVVUoxH0U6bz1hc5WTpOl0Sjjm0EiGwWZD2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});